language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
before_script: bundle update
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#bunto
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
  email:
    on_success: never
    on_failure: never

matrix:
  exclude:
    - rvm: 1.9.3
      env: BUNTO_VERSION=2.0.0
    - env: BUNTO_VERSION=1.0.0
      rvm: 2.1
    - rvm: 2.2
      env: BUNTO_VERSION=2.4

env:
  matrix:
    - ""
    - BUNTO_VERSION=2.4
    - BUNTO_VERSION=3.0.0
