language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - bundle update
script: script/cibuild
notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  exclude:
    - rvm: 1.9.3
      env: BUNTO_VERSION=1.0.0
    - rvm: 2.1
      env: BUNTO_VERSION=1.0.0
    - rvm: 2.2
      env: BUNTO_VERSION=1.0.0

env:
  matrix:
    - ""
    - BUNTO_VERSION=1.0.0
    - BUNTO_VERSION=2.0.0
