# Travis CI
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.3.0
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - bundle update
script: script/cibuild
notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  exclude:
    - rvm: 2.3.0
      env: BUNTO_VERSION=3.0.0
    - rvm: 2.3.1
      env: BUNTO_VERSION=3.2.1

env:
  matrix:
    - ""
    - BUNTO_VERSION=3.0.0
    - BUNTO_VERSION=3.2.1
